export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    customers: '/dashboard/customers',
    mangas: '/dashboard/mangas',
    settings: '/dashboard/settings',
    categories: '/dashboard/categories',
    authors: '/dashboard/authors',
    types: '/dashboard/types',
    groups: '/dashboard/groups',
    achievements: '/dashboard/achievements',
    companions: '/dashboard/companions',
    comments: '/dashboard/comments',
    mangaDetail: (id: string) => `/dashboard/mangas/${id}`,
  },
  errors: { notFound: '/errors/not-found' },
} as const;
